version: '3.7'
services:
    postgresql_db:
      image: postgres:14
      restart: always
      volumes:
         - ./data/db:/var/lib/postgresql/data
         - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      ports:
         - "5439:5432"
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=depixen
         - POSTGRES_PASSWORD=depixen-pass
    app:
      container_name: api
      build: .
      ports:
        - "8181:8181"
      restart: on-failure
      depends_on:
        - postgresql_db
      links:
        - postgresql_db
