CREATE TABLE IF NOT EXISTS tb_casestudy (
    id SERIAL PRIMARY KEY NOT NULL,
    title CHARACTER VARYING(45) NOT NULL,
    description CHARACTER VARYING(253) NOT NULL,
    imageurl CHARACTER VARYING(253) NOT NULL,
    createddate DATE NOT NULL
);

